# Generated by Django 3.1.1 on 2020-09-28 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('attachment', models.URLField()),
                ('image', models.URLField(default='https://github.com/Ajay2810-hub/Ebooks/raw/master/default/images/image_unavailable.jpg')),
                ('tags', models.URLField(default='https://github.com/Ajay2810-hub/Ebooks/blob/master/default/tags/tag.txt')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Book',
            },
        ),
        migrations.CreateModel(
            name='book_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Book Section',
            },
        ),
        migrations.CreateModel(
            name='book_download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'verbose_name': 'Book Download',
            },
        ),
    ]
